language: node_js

node_js:
  - "lts/*"
  - "node"


script:
  - yarn lint:check
  - yarn coverage
  - yarn test:size
  - yarn test:typescript
  - yarn flow
  - yarn test:prod
  - if [[ $TRAVIS_COMMIT_MESSAGE == *"#benchmark"* ]]; then npm run benchmark ; fi;

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn install --frozen-lockfile

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov/bin/codecov

cache:
  yarn: true
  directories:
    - node_modules
